remote_theme: pmarsceill/just-the-docs

title: "Biology 114: supplementary material"


footer_content: "Biology 114, Spring 2023. Supplementary material for hands-on exploration of evolution of cultural material.<br/>All material on this web site is © Neel Smith and available under the Creative Commons Attribution Share-Alike license <a href=\"https://creativecommons.org/licenses/by-sa/4.0/\">CC BY-SA 4.0 <img height=\"15\" width=\"80\" src=\"https://mirrors.creativecommons.org/presskit/buttons/80x15/png/by-sa.png\" /></a> on <a href=\"https://github.com/neelsmith/bio114\">github</a>."
